---
title: "Inequality Data"
output: html_document
date: "2023-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)
```

## Wealth gap across Regions, Countries, Gender


```{r}
wwdt <- read_csv("World Wealth Data.csv")


modified_names <- c("Time", "Country", "Country Code", "Total Wealth",
                    "Wealth per Capita",
                    "Produced Capital per Capita",
                    "Produced Capital",
                    "Human Capital (Female)",
                    "Human Capital (Male)",
                    "Human Capital",
                    "Human Capital per Capita",
                    "Human Capital (Employed Female)",
                    "Human Capital (Employed Male)",
                    "Human Capital per Capita (Employed Female)",
                    "Human Capital per Capita (Employed Male)")

# Modify column names in the dataframe
colnames(wwdt) <- modified_names

unique(wwdt$Country)

```


```{r}


wwdt <- wwdt %>%
  mutate(Continent = case_when(
    Country %in% c("Canada", "United States") ~ "North America",
    Country %in% c("Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay",
                   "Peru", "Suriname", "Uruguay", "Venezuela") ~ "South America",
    Country %in% c("Algeria", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cameroon", "Central African Republic",
                   "Chad", "Comoros", "Congo", "Côte d'Ivoire", "Djibouti", "Egypt", "Eswatini", "Ethiopia", "Gabon",
                   "Gambia", "Ghana", "Guinea", "Kenya", "Lesotho", "Liberia", "Madagascar", "Malawi", "Mali", "Mauritania",
                   "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Senegal", "Sierra Leone",
                   "South Africa", "Tanzania", "Togo", "Tunisia", "Uganda", "Zambia", "Zimbabwe","C?te d'Ivoire") ~ "Africa",
    Country %in% c("Albania", "Armenia", "Austria", "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Czech Republic",
                   "Denmark", "Estonia", "Finland", "France", "Georgia", "Germany", "Greece", "Hungary", "Iceland",
                   "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Netherlands", "North Macedonia",
                   "Norway", "Poland", "Portugal", "Romania", "Russia", "Serbia", "Slovak Republic", "Slovenia", "Spain",
                   "Sweden", "Switzerland", "Turkey", "Ukraine", "United Kingdom", "Belgium") ~ "Europe",
    Country %in% c("Australia", "Solomon Islands") ~ "Oceania",
    Country %in% c("Bangladesh", "China", "India", "Indonesia", "Iran", "Iraq", "Japan", "Kazakhstan", "Korea",
                   "Kyrgyz Republic", "Lao PDR", "Lebanon", "Malaysia", "Maldives", "Mongolia", "Myanmar", "Pakistan",
                   "Papua New Guinea", "Philippines", "Singapore", "Sri Lanka", "Taiwan", "Tajikistan", "Thailand",
                   "Timor-Leste", "Turkmenistan", "United Arab Emirates", "Uzbekistan", "Vietnam", "West Bank and Gaza",
                   "Yemen", "Azerbaijan", "Bahrain", "Belarus", "Belize", "Cambodia", "Costa Rica", "Côte d'Ivoire",
                   "Dem. Rep. Congo", "Dominican Republic", "El Salvador", "Guatemala", "Haiti", "Honduras", "Jamaica",
                   "Jordan", "Kuwait", "Mexico", "Moldova", "Nepal", "Nicaragua", "Oman", "Panama", "Qatar",
                   "Saudi Arabia", "The Gambia", "Trinidad and Tobago") ~ "Asia",
    TRUE ~ NA_character_
  ))


# Print countries with NA values in the Continent column
countries_with_na <- wwdt$Country[is.na(wwdt$Continent)]
print(countries_with_na)


# Filter countries with NA values in the Continent column
countries_with_na <- wwdt$Country[is.na(wwdt$Continent)]

# Print the country names
unique(countries_with_na)


```



```{r}
## Wealth Level across major countries

selected_countries <- c("United States", "United Kingdom", "China", "Brazil", "South Africa")

filtered_df <- wwdt[wwdt$Country %in% selected_countries, ]
filtered_df$Time <- as.numeric(filtered_df$Time)

ggplot(filtered_df, aes(x = Time, y = `Wealth per Capita`, color = Country, linetype = Country)) +
  geom_line(size = 1.2) +
  labs(x = "Time", y = "Wealth per Capita", color = "Country",
       title = "Wealth per Capita Level across Major Countries over Time") +
  scale_linetype_manual(values = c("solid", "dashed", "dotted", "dotdash", "longdash")) + scale_y_continuous(labels = function(x) paste0(x / 1000, "k")) +
  theme_bw()


```

```{r}
## Wealth Level across continents


# Calculate the average wealth per capita by continent and year
continent_avg <- wwdt %>%
  group_by(Continent, Time) %>%
  summarize(Avg_Wealth_per_Capita = mean(`Wealth per Capita`))


continent_avg <- na.omit(continent_avg)

ggplot(continent_avg, aes(x = Time, y = Avg_Wealth_per_Capita, color = Continent, linetype = Continent)) +
  geom_line() +
  labs(title = "Average Wealth per Capita by Continent over Time", x = "Year", y = "Average Wealth per Capita") +
  scale_color_discrete(name = "Continent") +
  scale_linetype_manual(values = c("solid", "dashed", "dotted", "dotdash", "longdash", "twodash")) +
   scale_y_continuous(labels = function(x) paste0(x / 1000, "k")) +
  theme_minimal()


```
```{r}
## Gender Gap in USA

colnames(wwdt)

library(ggplot2)

# Create the usa dataframe with columns for employed female and employed male
usa <- wwdt %>%
  filter(Country == "United States") %>%
  select(Time, `Human Capital per Capita (Employed Female)`, `Human Capital per Capita (Employed Male)`) %>%
  tidyr::gather(type, value, -Time)

# Plot the data
ggplot(usa, aes(Time, value, fill = type)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Human Capital per Capita (Employed Female and Male) in the United States",
       x = "Year",
       y = "Human Capital per Capita",
       fill = "") +
  scale_fill_manual(values = c("Human Capital per Capita (Employed Female)" = "red", "Human Capital per Capita (Employed Male)" = "green"),
                    labels = c("Female", "Male")) +
  scale_y_continuous(labels = function(x) paste0(x / 1000, "k")) +  # Set the y-axis labels to represent values in thousands
  theme_minimal()



# Plot the data
ggplot(usa, aes(Time, value, color = type)) +
  geom_line() +
  labs(title = "Human Capital per Capita across Genders in the United States",
       x = "Year",
       y = "Human Capital per Capita",
       color = "") +
  scale_color_manual(values = c("Human Capital per Capita (Employed Female)" = "red", "Human Capital per Capita (Employed Male)" = "green"),
                     labels = c("Female", "Male")) +
  scale_y_continuous(labels = function(x) paste0(x / 1000, "k")) +  # Set the y-axis labels to represent values in thousands
  theme_minimal()


```



## Wealth Across Religion
```{r}
#relig_income

rdf <- relig_income

colnames(rdf)



# Compute average income for each religion
avg_income <- rdf_mid %>%
  group_by(religion) %>%
  summarize(Average_Income = sum(Mid_Value * (`<$10k` + `$10-20k` + `$20-30k` + `$30-40k` + `$40-50k` + `$50-75k` + `$75-100k` + `$100-150k` + `>150k`)) / sum(`<$10k` + `$10-20k` + `$20-30k` + `$30-40k` + `$40-50k` + `$50-75k` + `$75-100k` + `$100-150k` + `>150k`), na.rm = TRUE)

# Plot the data
ggplot(avg_income, aes(x = religion, y = Average_Income)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(title = "Average Income by Religion in the US",
       x = "",
       y = "Average Income (K)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_text(aes(label = sprintf("%.1f", Average_Income)), vjust = -0.5, size = 3) +
  coord_cartesian(ylim = c(0, max(avg_income$Average_Income))) +
  scale_y_continuous(labels = function(x) paste0(x, "k"))
```



## Wealth Across Races and Ethinic Groups
```{r}
rmdf <- read_csv("interactive_bulletin_charts_racecl4_median.csv")

colnames(rmdf)

```


```{r}

# Plot the assets for each category by year
ggplot(rmdf, aes(x = year, y = Assets , color = Category)) +
  geom_line() +
  labs(title = "Wealth Gap across Races in the US",
       x = "Year",
       y = "Assets by thousands (K)") +
  scale_color_discrete(name = "Ethinic Groups") +
  theme_minimal()
```



## Chart Remake Disparity

```{r}
#Table 1
table1 <- data.frame(
  Year = c(2010, 2013, 2016, 2019),
  Ethnicity = c("Non-Latinx white", "Non-Latinx white", "Non-Latinx white", "Non-Latinx white", 
                "Non-Latinx black", "Non-Latinx black", "Non-Latinx black", "Non-Latinx black",
                "Latinx", "Latinx", "Latinx", "Latinx"),
  In_Labor_Force = c(82.23, 81.81, 83.48, 84.68,
                     72.78, 72.03, 76.30, 80.49,
                     85.84, 84.72, 86.10, 86.77),
  Working_Class_LF = c(53.35, 52.91, 52.67, 53.32,
                       68.44, 58.50, 65.36, 63.59,
                       78.53, 78.74, 79.87, 77.73),
  Tech_Sales_Service = c(50.47, 50.90, 51.60, 49.78,
                         59.37, 57.21, 64.22, 52.00,
                         45.83, 41.10, 46.14, 47.88),
  Manufacturing_Farm_Other = c(49.53, 49.10, 48.40, 50.22,
                               40.63, 42.79, 35.78, 48.00,
                               54.17, 58.90, 53.86, 52.12),
  Professional_Class_LF = c(46.65, 47.09, 47.33, 46.68,
                            31.56, 41.50, 34.64, 36.41,
                            21.47, 21.26, 20.93, 22.27))

# Convert the Year column to factor for categorical representation
table1$Year <- as.factor(table1$Year)

# Create the line plot
ggplot(table1, aes(x = Year, y = In_Labor_Force, group = Ethnicity, linetype = Ethnicity, Color = Ethnicity)) +
  geom_line() +
  labs(title = "Change of Ethinic Groups in Labor Force over Time",
       x = "Year", y = "% of Population In Labor Force") +
  scale_linetype_manual(values = c("solid", "dashed", "dotted")) +
  theme_minimal()



#change the y scale.

```

```{r}
table2 <- data.frame(
  Item = c("Liquid assets", "Stocks/bonds/CDs", "Retirement account/pensions",
           "Life insurance/other financial asset", "Real estate", "business",
           "Vehicles", "Other nonfinancial", "Housing debt",
           "Other lines of credit/other", "Credit card debt", "Education debt",
           "Vehicle debt"),
  `White` = c(0.03, -0.14, -0.03, -0.07, -0.03, 0.06,
              0, -0.02, -0.12, 0.01, 0.13, 0.09, 0.15),
  `Black` = c(0.17, -0.22, 0.07, -0.08, -0.15, -0.4,
              0.02, 0.25, -0.33, 0.01, 0.37, 0.15, 0.19),
  `Latinx` = c(0.14, -0.22, -0.16, 0.05, 0.09, 0.14,
               0.02, 0.96, -0.14, 0.25, 0.26, 0.29, 0.6)
)

table2 <- t(table2)
# Set the column names as the first row
colnames(table2) <- table2[1, ]

# Remove the first row
table2 <- table2[-1, ]


```


```{r}
table_tr <- as.data.frame(table2)

# Convert the row names to a new column "Race"
table_tr$Race <- row.names(table_tr)

# Reshape the dataframe from wide to long format
long_df <- reshape2::melt(table_tr, id.vars = "Race")

# Create the clustered bar plot
ggplot(long_df, aes(x = variable, y = value, fill = Race)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Clustered Bar Plot - Assets by Race",
       x = "Asset Type", y = "Value") +
  scale_fill_manual(values = c("#FF0000", "#00FF00", "#0000FF")) + 
  coord_cartesian(ylim = c(-1, 1))  # Adjust y-axis limits
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Convert 'value' column to numeric
long_df$value <- as.numeric(as.character(long_df$value))

# Create the clustered bar plot
ggplot(long_df, aes(x = variable, y = value, fill = Race)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Change of Assets by Races 2010 - 2019",
       x = "Asset Type", y = "Change of Shares") +
  scale_fill_manual(values = c("#FF0000", "#00FF00", "#0000FF")) + 
  scale_y_continuous(limits = c(-1, 1), breaks = seq(-1, 1, by = 0.2), labels = function(x) ifelse(x < 0, abs(x), x)) +
  coord_cartesian(ylim = c(-1, 1)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


# seperate debt and assets
# percentage change in titles
```


```{r}
# Table 4

table4 <- data.frame(
  Ethnicity = c(rep("White", 4), rep("Black", 4), rep("Latinx", 4)),
  Year = rep(c(2010, 2013, 2016, 2019), 3),
  Working_Class = c(0.20, 0.20, 0.21, 0.22, 0.08, 0.10, 0.06, 0.09, 0.04, 0.03, 0.06, 0.07),
  Professional_Class = c(0.26, 0.27, 0.23, 0.25, 0.14, 0.08, 0.09, 0.08, 0.08, 0.12, 0.06, 0.12),
  Median_Working_Class = c(0.15, 0.18, 0.17, 0.18, 0.06, 0.07, 0.03, 0.07, 0.04, 0.03, 0.06, 0.03),
  Median_Professional_Class = c(0.21, 0.25, 0.24, 0.28, 0.07, 0.05, 0.05, 0.08, 0.05, 0.08, 0.13, 0.07),
  Nonzero_Inheritance_Working_Class = c(29377, 56063, 42615, 40000, 29377, 46169, 21307, 35000, 12926, 14291, 42615, 35000),
  Nonzero_Inheritance_Professional_Class = c(70506, 72552, 58595, 70000, 72856, 65956, 46876, 63000, 52879, 109927, 51307, 110000)
)


library(ggplot2)

# Select columns 'Ethnicity', 'Year', and 'Working Class'
selected_df <- table4[, c("Ethnicity", "Year", "Working_Class")]


ggplot(selected_df, aes(x = Year, y = `Working_Class`, color = Ethnicity)) +
  geom_line() +
  labs(title = "Percentage of Reciving Inheritance for Different Ethinic Groups",
       x = "Year", y = "Percentage") +
  scale_x_continuous(breaks = unique(selected_df$Year), labels = function(x) format(x, format = "%0.0f")) +
  theme_minimal()

#delete "of"

#amounts

#vivo transfer



```



```{r}
# ICPSR Inida Data

# South Africa Inequality (WID), socio-identity

# Brazil, socio-identity

# voyage of exploiatation, inequality

# speculative assets, introducing what is crypto,



```

